### ISSUE TITLE
[QUESTION/PROPOSAL] move social bar to config.toml

### ISSUE THREAD

**Issue by yamila-moreno** [kakawait/hugo-tranquilpeak-theme#124]
Hi! I have a question and two proposal (I'm offering for both):

**Question**Those params:
```
comments     Disable the comment of the post.
showDate     true: Show the date when true (default)
showTags     true: show tags of this page. Default behavior: true
showPagination     true: show pagination. Default behavior: true
showSocial     true: show social button such as share on Twitter, Facebook... Default behavior: true
```
can only be set in each post, and you cannot set it for the whole blog, is that correct? Being so, I can set it in archetypes, but a new value added to archetypes only would apply to the new posts, and the user should have to change manually the frontmatter of each post.

My guess is that those variables are generally meant for the whole blog. What do you think?

My first **proposal** (and if you like it, I can make a PR) would be:
- make those params general (move them to config.toml)
- change the layouts to read the .Site.Params...
- update the documentation

My doubt is how to enable the chance to overrite the general set in an specific post (I'm thinking of disabling comments in a post, or something like that). AFAIK, I cannot override the same param in the post so my approach would be to check with an "and" (general param is not false and post param is not false).

Following this, my second **proposal** (again, if you like it, I can make a PR) would be:
- create new social params, like: show_twitter, show_facebook, show_googleplus to choose which social networks to show
- this would also be set globally and the user could override in an specific post
- this would enable the chance to newbies to contribute with more social networks :)

I hope this text-wall is not overwhelming! :) Thanks for your time 👍

**Comment by kakawait** [comment]
Thank for feedback

> My guess is that those variables are generally meant for the whole blog. What do you think?

Those options are pretty new, but its was designed for _no blog post page_. Since this theme is for blog theme I didn't think is essential to set it globally since is for edge case.

However for `comment` if you don't set any `disqusShortname` (global configuration) it should not display comment on every posts.

In addition, I thought user can use `archetype` feature to add default post _front matter_ setting, thus if you expect to do not have _social_ button you can create your own `archetype` that set `showSocial` to `false`.

> Being so, I can set it in archetypes, but a new value added to archetypes only would apply to the new posts, and the user should have to change manually the front matter of each post.

You're correct, but I think today this theme has many many (too much) configuration so I tried to limit too much global configuration when is not _essential_ (from my point of view).

> create new social params, like: show_twitter, show_facebook, show_googleplus to choose which social networks to show.

Yes we can split `show_social` by each _social provider_ to get better control, but as above I don't think we really need to set it globally. 

> this would enable the chance to newbies to contribute with more social networks :)

I'm not sure how splitting configuration will help adding other social providers (I mean we need to change template, as same as with `enable_social`)

**Comment by yamila-moreno** [comment]
Hi, thank you for the time answering and for the explanations. I understand your position, and I'll try to contribute with other issues. 👍
