### ISSUE TITLE
Removing (or hiding) the 'Posts' entry on the Archives page

### ISSUE THREAD

**Issue by facingBackwards** [kakawait/hugo-tranquilpeak-theme#203]
There might be a setting I'm missing somewhere but is it possible to hide the Posts link or stop it appearing in the Archive view?

Also thanks for the theme. It's a great change coming from WP.

### Configuration

 - OS: Ubuntu 16.04 
 - Chrome 61.0.3163.91
 - Hugo 0.27.1
 - TranquilPeak 0.4.1-beta
 - Reproduce in demo? Yes
 
### Actual behavior
From the homepage, select Archives. Most recent month has entry labelled Posts as well as the posts from that month. Link takes you to /post which appears the same as home.

### Expected behavior
Only the posts should appear.

### Steps to reproduce the behavior
Click Archives

**Comment by kakawait** [comment]
Is not correct behavior lol. You just find a bug. `Posts` should not be here. I think is since Hugo 0.18 when everything becomes a `Page` http://bepsays.com/en/2016/12/19/hugo-018/

I will try to fix it. 

Funny thing is that I'm use to check archive page for no regression but I never noticed that link to `posts`
