### ISSUE TITLE
Code highlight not working for F# langauge

### ISSUE THREAD

**Issue by kunjee17** [kakawait/hugo-tranquilpeak-theme#244]
### Configuration

 - **Windows 10**: 
 - **Firefox 57**:
 - **Hugo version - 0.30.2**:
 - **Tranquilpeak version- 0.4.3-BETA**: 
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: No
 

### Actual behavior
I am using F# code snippets in my blog at kunjan.in. Code highlighting is not working with both Highlightjs and prismjs.
### Expected behavior
Code highlight should be working for every language supported by above library. Or provide documentation to change things to support it.
### Steps to reproduce the behavior
Use any F# code and it will not work.

**Comment by kakawait** [comment]
@kunjee17 I think is related to _Highlight.js_ is not bundle (by default) with `F#` support.

You can add 

```toml
[params]
  customJS = ["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/fsharp.min.js"]
```

**ATTENTION** you can't use new syntax as describe here https://github.com/kakawait/hugo-tranquilpeak-theme/issues/186#issuecomment-346593802 because there is currently a bug on Chrome (see https://github.com/kakawait/hugo-tranquilpeak-theme/issues/186#issuecomment-347985905 to understand why, **but I will fix it on next release 0.4.4-BETA**)

**Comment by kunjee17** [comment]
@kakawait that thing did the trick. It worked. Thanks... You can close the issue if you like. Or can keep it open if you like to tag it along for next version.

**Comment by kakawait** [comment]
Glad to heard is working for you. I'm closing
