### ISSUE TITLE
Add a search bar

### ISSUE THREAD

**Issue by dawnarc** [kakawait/hugo-tranquilpeak-theme#30]
A search bar is useful to search article in blog.

**Comment by kakawait** [comment]
I was thinking to implement search as same as original theme. Furthermore I would integrate [Algolia](https://www.algolia.com/) service, because in addition to have input search (in top bar or not) we need a index.

@dawnarc as preview you can try search from original theme demo site http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/ 

Simply click on *search* on side bar or simply press `s` key to open search dialog.

Could you give your feedback? Because as I said is what I would implement in futur.

**Comment by dawnarc** [comment]
@kakawait OK, I see. Thx very much~

**Comment by kakawait** [comment]
@dawnarc If you are ok with futur implemention I will close this issue in favor of #8 (duplicate)?

**Comment by dawnarc** [comment]
@kakawait OK, no problem. Have a nice day!

**Comment by kakawait** [comment]
dup of #8
