### ISSUE TITLE
Sidebar/header bug on small screen

### ISSUE THREAD

**Issue by adrianriyadi** [kakawait/hugo-tranquilpeak-theme#318]
### Configuration

 - **Operating system with its version**: Ubuntu 18.04
 - **Browser with its version**: Google Chrome v.71
 - **Hugo version**: 0.52 
 - **Tranquilpeak version**: 0.4.3-BETA 
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: YES
 

### Actual behavior
Header bar is not precise after swiped in small screen resolution

![untitled](https://user-images.githubusercontent.com/24358334/50405977-27ee0800-07ef-11e9-9f56-0611e2efa083.png)

### Expected behavior
Header bar is precise like in the beginning

![untitled](https://user-images.githubusercontent.com/24358334/50406006-a3e85000-07ef-11e9-9b1d-ba9e581ac783.png)

### Steps to reproduce the behavior
1. Visit website
2. Click hamburger (collapse/expand) button
3. Swipe the sidebar
4. Bug occurs

**Comment by kakawait** [comment]
Ok I was able to reproduce I'll try to fix it

**Comment by kakawait** [comment]
@adrianriyadi in fact swipe is not really a swipe is was a bug introduced before.

I say is not really a swipe because is not interacting with swipe event, is was just page width + overflow issue that allow you to scroll horizontally and give you impression that you're swipping.

In first time I'll fix that issue by fixing that scrolling (aka fake swipe) issue

**Comment by kakawait** [comment]
related to #342

**Comment by adrianriyadi** [comment]
Yeah you're right.. When I collapsed the sidebar with a click, this bug isn't appear at all and the page acts normally.
