### ISSUE TITLE
Sidebar : swipe behaviour on iOS and MacOS Safari overlay incorrectly remains present 

### ISSUE THREAD

**Issue by d3vAdv3ntur3s** [kakawait/hugo-tranquilpeak-theme#342]
### Configuration

 - **Browser with its version**: `iOS Safari 12 or MacOS Safari 12` 
 - **Hugo version**: `Hugo Static Site Generator v0.55.6/extended darwin/amd64 BuildDate: unknown`
 - **Tranquilpeak version**: `0.4.4-BETA`

 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
![May-24-2019 15-25-48](https://user-images.githubusercontent.com/6087007/58335115-ca5ef580-7e38-11e9-8e07-9beaf5865b31.gif)
 

### Actual behavior
**Refer to Gif above**
On mobile view whilst on safari when the menu is opened, a swipe left on Safari will allow the menu content to remain     

### Expected behavior
On swipe the menu should disappear the same way clicking elsewhere or the mobile menu  icon

### Steps to reproduce the behavior
Launch iOS or MacOS Safari (Window size will need to go to mobile view)
Goto: https://tranquilpeak.kakawait.com
Open the menu 
Then swipe menu to the left

**Comment by kakawait** [comment]
@raztiff, in fact swipe is not really a swipe is was a bug introduced before.

I say is _not really a swipe_ because is not interacting with `swipe` event, is was just page `width` + `overflow` issue that allow you to scroll horizontally and give you impression that you're swipping.

In first time I'll fix that issue by fixing that scrolling (aka fake _swipe_) issue

**Comment by raztiff** [comment]
Thanks for looking into the issue :)
