### ISSUE TITLE
Add support for gitment commenting system

### ISSUE THREAD

**Issue by hellt** [kakawait/hugo-tranquilpeak-theme#344]
Is it possible to add gitment comment engine? It's a perfect alternative to the privacy-disrespectful Disqus and is backend-less. 

Gitment would make this theme even more awesome and appealing for IT pros

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a public GitLab instance of [Staicman](https://staticman.net).  While Gitment supports GitHub only, Staticman supports both GitHub & GitLab.

Staticman makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments, apart from improving the site's SEO.

**Comment by kakawait** [comment]
BTW Gitment seems to be dead https://github.com/imsun/gitment/issues/200

There is other alternative I prefer focus on no-dead project (like @VincentTam one)

**Comment by hellt** [comment]
yes, I integrated gitalk to this theme, it was easier than it sounded
