### ISSUE TITLE
could you add more function for this theme?

### ISSUE THREAD

**Issue by iFence** [kakawait/hugo-tranquilpeak-theme#369]
### Configuration

 - **Operating system with its version**: Win10
 - **Browser with its version**:chrome 76
 - **Hugo version**: v0.56.3-F637A1EA
 - **Tranquilpeak version**: 0.4.6-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Expected behavior
I'm a China user.thank you. this theme is awesome. In China disqus_thread is not work ,but **utteranc** can work good. could you add this comment tool support for this theme?

another question: Article does not support counting，could you add this?
I find another theme,support above function,you can refer to it.website:https://github.com/rujews/maupassant-hugo/blob/master/README_EN.md

thank you again.

### Steps to reproduce the behavior

**Comment by kakawait** [comment]
Hi @iFence 

About alternative to disqus there is 2 new comings on next release `0.5.0` directly inherited from upstream project https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak

1. Gitment
2. Gitalk

For other integration we can think about but is not top priority now since I have lot of work to do before.

About _counting_ I'm not totally sure what your expecting and _maupassant_ sample unfornately is not in english and I'm not able to read it.

Do you mean word counting? Time counting? other

**Comment by iFence** [comment]
sorry,I'm late.thank you，Looking forward to the new version.
"counting"，I mean if someone clicks on my article, the blog can see the article traffic.
e.g. when I finish a blog.no one reads,on one visits,so its counting is zero.
When the first person read my blog，this blog has one click ,its counting is one.
Similar to statistical website traffic
sorry,my English is poor.could you feel me ?

**Comment by kakawait** [comment]
@iFence I don't think is possible to do _counting_ with Hugo because is static site generator there is no backend/server that could store and increment that state/counter.

Only thing you could do is add Google Analytics to see your traffic but I don't think you will be able to expose result on your blog directly
