### ISSUE TITLE
How to set custom font in this theme?

### ISSUE THREAD

**Issue by dawnarc** [kakawait/hugo-tranquilpeak-theme#52]

**Comment by kakawait** [comment]
You should fork it and customize https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/src/scss/utils/_variables.scss

Then rebuild the theme, please read https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/developer.md if you want to customize `scss`/`css`

**Comment by dawnarc** [comment]
@kakawait I see, Thx very much!

**Comment by kakawait** [comment]
There is no option in `config.toml` to change it.

You may try to create your own `.scss` file in https://github.com/kakawait/hugo-tranquilpeak-theme/tree/master/src/scss/utils like `_variables_custom.scss` and import it just after https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/src/scss/tranquilpeak.scss#L3

Thus when you will update theme it will be easy to resolve conflict because if I change `_variables.scss` you may want to retrieve modification.

**Comment by dawnarc** [comment]
@kakawait Good idea! Thx again!

**Comment by kakawait** [comment]
I will close issue if you have trouble with *dev* setup fill free to open other issue.

Actually every `scss` files (except `custom.scss`) are strictly equals to original theme (in order to allow retrieve update from original theme) so I may not control modifications! Thus the idea to have an override file seems the best way for you.

**Comment by kakawait** [comment]
@dawnarc theme is not using `scss` directly but file on `static`, but if you look on `static` https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/static/css/style-zfzvxnwixwz6qe7xv3xz1eyvlzc7cdfoxrgduk75zpqxib0hatbphiq9sddx.min.css is minified.

You can edit it directly but is not a good idea, best idea is to set up *dev* env, edit `.scss` and run `grunt` task that will concat/minified every `.scss` to `static/css/style-XXXX.css`

**Comment by dawnarc** [comment]
@kakawait OK, Ty!
