### ISSUE TITLE
Failed to load translations in file "en.yaml"

### ISSUE THREAD

**Issue by libmb** [kakawait/hugo-tranquilpeak-theme#84]
I tried to build a site with this theme and was given the following error:
```
$ hugo -d ../libmb.github.io/ -t hugo-tranquilpeak-theme -D
Started building sites ...
Error: Error building site: Failed to load translations in file "en.yaml": failed to load en.yaml because yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `en-us.yaml` into []map[string]interface {}
```
I noticed that the en.yaml file did not contain valid yaml but looked like it was linking to the en-us.yaml file. I copied the contents of en-us.yaml to en.yaml and I was able to build my site.

**Comment by kakawait** [comment]
@libmb are you using Windows OS?

**Comment by blaubaer** [comment]
@kakawait: Yes! I experienced the same problem here on my machine. The problem is the link that the version of Git for Windows does not support and simply creates a file ``en.yaml`` with the content ``en-us.yaml``. Is this file really required? I could perfectly generate every site also if ``en.yaml`` does not exist.

**Comment by kakawait** [comment]
Ok thank you for feedback, you confirmed my hypothesis.

I will find another solution because *Windows* support is as important as other platform.
